export default {
  FETCH_GENRES_FAILURE: `FETCH_GENRES_FAILURE`,
  FETCH_GENRES_SUCCESS: `FETCH_GENRES_SUCCESS`,
  FETCH_GENRES_REQUEST: `FETCH_MOVIES_REQUEST`,
  CHANGE_ACTIVE_GENRE: `CHANGE_ACTIVE_GENRE`,
};
